### ISSUE TITLE
请教一下算法思路流程

### ISSUE THREAD

**Issue by Peins** [Licmjy-CU/BiAITstar#3]

**Comment by Licmjy-CU** [comment]
尊敬的读者，您好！首先感谢您阅读我的代码和方法。以下图片是我刚刚运行了一次的结果：

[PastedGraphic-3.png]

在这一测试中，环境使用了github代码中设置的环境，所有参数和github上公开的代码中的保持一致，使用了release模式进行编译（在CMakeLists文件中可调整），平台选用了带有M1Pro芯片的Mac。

不可否认的是，双向的改进思路可以提高overall performance，但是即使是几年前提出的MM算法族，在一些特定场景中也比不上Astar算法族的效率。同理可以推及BiAIT*和AIT*算法。

至于为什么没有include AITstar的工程代码，主要还是因为AITstar的代码虽然写的很漂亮，但是member functions之间耦合严重，很难直接通过继承或者复合的方式来进行扩展。另外就是开发过程中使用了一个我之前用opencv给ompl写的可视化库，用于debug。所以综合考虑之下我选择了另起炉灶，这主要是基于开发效率以及AITstar的可扩展性的考虑。出于保持一致性的目的，我的代码中class和member functions使用了和AITstar相同的命名习惯。建议对照ompl库中的AITstar的代码进行阅读。



On 2 Aug 2023, at 8:49 PM, PEIN ***@***.***> wrote:



请教大佬一下该算法的思路流程，(因为没有看到include AITstar的类)，这个算法和AITstar有什么关系吗？如果有，怎么改进的？
还有我运行出的结果迭代次数从默认的1000设置为5000才能跑出结果，用的时间也挺久，60秒左右，感觉成功率和速度不是特别好啊，我需要设置其他什么参数吗？
